pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'
    }

    environment {
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {
        stage('Build') {
            steps {
                echo 'Compilation avec Maven...'
                dir('jenkins') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Analyse SonarQube') {
            steps {
                echo 'Analyse SonarQube...'
                dir('jenkins') {
                    sh '''
                        mvn sonar:sonar \
                          -Dsonar.projectKey=demo-java-app \
                          -Dsonar.host.url=http://localhost:9000 \
                          -Dsonar.login=$SONAR_TOKEN
                    '''
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                echo 'Build et push de l\'image Docker...'
                dir('jenkins') {
                    sh 'docker build -t monimage .'
                    // Ajoute ici ton docker push si besoin
                }
            }
        }
    }
}
