pipeline {
    agent any

    environment {
        SONAR_TOKEN = credentials('sonarqube')
        DOCKER_CREDENTIALS_ID = 'dockerhub'
        DOCKER_IMAGE = 'nadouille/devops-demo:latest'
    }

    tools {
        maven 'Maven 3.9.6'
        jdk 'JDK 17'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Compilation avec Maven...'
                sh 'mvn clean install'
            }
        }

        stage('Analyse SonarQube') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        def image = docker.build(DOCKER_IMAGE)
                        image.push()
                    }
                }
            }
        }
    }
}
