pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'
    }

    environment {
        SONAR_TOKEN = credentials('sonarqube')
    }

    stages {
        stage('Build') {
            steps {
                echo 'Compilation avec Maven...'
                sh 'mvn clean package'
            }
        }

        stage('Analyse SonarQube') {
            steps {
                echo 'Analyse SonarQube...'
                sh '''
                    mvn sonar:sonar \
                      -Dsonar.projectKey=demo-java-app \
                      -Dsonar.host.url=http://sonarqube:9000 \
                      -Dsonar.login=$SONAR_TOKEN
                '''
            }
        }

        stage('Docker Build & Push') {
            environment {
                DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
            }
            steps {
                echo 'Connexion à Docker Hub...'
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                
                echo 'Build de l\'image Docker...'
                sh 'docker build -f ci/Jenkins/Dockerfile -t monimage:v1.0 .'
                
                echo 'Push de l\'image Docker...'
                sh 'docker push monimage:v1.0'
            }
        }
    }
}
